select
	TIA.COUNTER, 
  TIA.C_ISSUE,
  TIA.C_CLOSE_OPER, 
  TIA.C_OPEN_OPER, 
  TIA.C_USER, 
  TIA.OPEN_TS, 
  TIA.CLOSE_TS,
  TIA.C_OPEN_MEETING,
  TIA.C_CLOSE_MEETING,
  TIA.NOTE,
  TU.LOGIN as USERLOGIN,
  TUO.LOGIN as OPERATOROPENLOGIN,
  TUC.LOGIN as OPERATORCLOSELOGIN,
  TU.LOGIN as USERFIRSTNAME,
  TUO.LOGIN as OPERATOROPENFIRSTNAME,
  TUC.LOGIN as OPERATORCLOSEFIRSTNAME,
  TU.LOGIN as USERLASTNAME,
  TUO.LOGIN as OPERATOROPENLASTNAME,
  TUC.LOGIN as OPERATORCLOSELASTNAME
from zhaba.tbl_issueassign as TIA
  join tbl_user as TU on TU.COUNTER = TIA.C_USER
  left join tbl_user as TUO on TUO.COUNTER = TIA.C_OPEN_OPER
  left join tbl_user as TUC on TUC.COUNTER = TIA.C_CLOSE_OPER
WHERE 
  (TIA.C_ISSUE = ?pIssue) 
  AND (TIA.OPEN_TS <= ?dateUTC) AND (?dateUTC <= TIA.CLOSE_TS OR TIA.CLOSE_TS IS NULL)
ORDER BY TIA.OPEN_TS DESC