select tia.*,
 tu.LOGIN AS USERLOGIN,
 tu.FIRST_NAME AS USERFIRSTNAME,
 tu.LAST_NAME AS USERLASTNAME,
 tuo.LOGIN AS USEROPENLOGIN,
 tuo.FIRST_NAME AS USEROPENFIRSTNAME,
 tuo.LAST_NAME AS USEROPENLASTNAME,
 tuc.LOGIN AS USERCLOSELOGIN,
 tuc.FIRST_NAME AS USERCLOSEFIRSTNAME,
 tuc.LAST_NAME AS USERCLOSELASTNAME
from tbl_issueassign tia
JOIN tbl_user tu ON tu.COUNTER = tia.C_USER
LEFT JOIN tbl_user tuo ON tuo.COUNTER = tia.C_OPEN_OPER
LEFT JOIN tbl_user tuc ON tuc.COUNTER = tia.C_CLOSE_OPER
where C_ISSUE = ?C_Issue