select tia.*,
 tu.LOGIN AS USERLOGIN,
 tu.FIRST_NAME AS USERFIRSTNAME,
 tu.LAST_NAME AS USERLASTNAME,
 tuo.LOGIN AS OPERATOROPENLOGIN,
 tuo.FIRST_NAME AS OPERATOROPENFIRSTNAME,
 tuo.LAST_NAME AS OPERATOROPENLASTNAME,
 tuc.LOGIN AS OPERATORCLOSELOGIN,
 tuc.FIRST_NAME AS OPERATORCLOSEFIRSTNAME,
 tuc.LAST_NAME AS OPERATORCLOSELASTNAME
from tbl_issueassign tia
JOIN tbl_user tu ON tu.COUNTER = tia.C_USER
LEFT JOIN tbl_user tuo ON tuo.COUNTER = tia.C_OPEN_OPER
LEFT JOIN tbl_user tuc ON tuc.COUNTER = tia.C_CLOSE_OPER
where C_ISSUE = ?C_Issue